[theme]
# Resetting to default settings before applying custom theme
base = "light"
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font = "sans serif"
